use super::traits;
use crate::errors::Error;

use std::{fmt, io};
use zeroize::Zeroizing;

use pgp::{
    composed::{Deserializable, SignedPublicKey, SignedSecretKey},
    crypto::{hash::HashAlgorithm, public_key::PublicKeyAlgorithm},
    packet::{
        PacketTrait, SecretKey, SecretSubkey, SignatureConfig, SignatureType, Subpacket,
        SubpacketData,
    },
    types::{KeyDetails, KeyVersion, Password, PublicParams, SigningKey},
};

/// An enum that can hold either a primary key or a subkey for signing.
#[derive(Clone, Debug)]
enum AnySigningKey {
    Primary(SecretKey),
    Sub(SecretSubkey),
}

macro_rules! delegate_any_signing_key {
    ($self:expr, $method:ident $(, $arg:expr)*) => {
        match $self {
            AnySigningKey::Primary(k) => k.$method($($arg),*),
            AnySigningKey::Sub(k) => k.$method($($arg),*),
        }
    };
}

impl KeyDetails for AnySigningKey {
    fn version(&self) -> KeyVersion {
        delegate_any_signing_key!(self, version)
    }

    fn legacy_key_id(&self) -> pgp::types::KeyId {
        delegate_any_signing_key!(self, legacy_key_id)
    }

    fn fingerprint(&self) -> pgp::types::Fingerprint {
        delegate_any_signing_key!(self, fingerprint)
    }

    fn algorithm(&self) -> PublicKeyAlgorithm {
        delegate_any_signing_key!(self, algorithm)
    }

    fn created_at(&self) -> pgp::types::Timestamp {
        delegate_any_signing_key!(self, created_at)
    }

    fn legacy_v3_expiration_days(&self) -> Option<u16> {
        delegate_any_signing_key!(self, legacy_v3_expiration_days)
    }

    fn public_params(&self) -> &PublicParams {
        delegate_any_signing_key!(self, public_params)
    }
}

impl SigningKey for AnySigningKey {
    fn sign(
        &self,
        passwd: &Password,
        hash_alg: HashAlgorithm,
        digest: &[u8],
    ) -> pgp::errors::Result<pgp::types::SignatureBytes> {
        match self {
            Self::Primary(k) => SigningKey::sign(k, passwd, hash_alg, digest),
            Self::Sub(k) => SigningKey::sign(k, passwd, hash_alg, digest),
        }
    }

    fn hash_alg(&self) -> HashAlgorithm {
        delegate_any_signing_key!(self, hash_alg)
    }
}

fn validate_algorithm(alg: PublicKeyAlgorithm) -> Result<(), Error> {
    match alg {
        PublicKeyAlgorithm::RSA
        | PublicKeyAlgorithm::EdDSALegacy
        | PublicKeyAlgorithm::Ed25519
        | PublicKeyAlgorithm::ECDSA
        | PublicKeyAlgorithm::MlDsa65Ed25519
        | PublicKeyAlgorithm::MlDsa87Ed448 => Ok(()),
        algorithm => Err(Error::UnsupportedPGPKeyType(algorithm)),
    }
}

/// Signer implementation using the `pgp` crate.
///
/// This supports either ascii armored key files (commonly with the file extension `.asc`
/// as generated by e.g. `gpg`), including keyring files with multiple certificates, or
/// bare key objects via [`Signer::new`].
///
/// When loaded from an ascii armored key, the signer retains the full key structure,
/// enabling subkey selection via [`Signer::with_signing_key`] and automatic inclusion
/// of the signer's user ID in signatures.
#[derive(Clone, Debug)]
pub struct Signer {
    /// All signed keys from the keyring (from load_from_asc).
    signed_keys: Vec<SignedSecretKey>,
    /// The actual key used for signing (primary or selected subkey).
    signing_key: AnySigningKey,
    /// The signer's user ID, included in signatures when available.
    user_id: Option<Vec<u8>>,
    key_passphrase: Option<String>,
}

impl traits::Signing for Signer {
    type Signature = Vec<u8>;

    fn sign(&self, data: impl io::Read, t: crate::Timestamp) -> Result<Self::Signature, Error> {
        let mut sig_cfg = Self::prepare_signer_configuration(&self.signing_key, t)?;

        if let Some(ref uid) = self.user_id {
            sig_cfg
                .hashed_subpackets
                .push(Subpacket::regular(SubpacketData::SignersUserID(
                    uid.clone().into(),
                ))?);
        }

        let pw = self.key_passphrase.clone().unwrap_or_default();
        let passwd = Zeroizing::new(pw.into());

        let signature_packet = sig_cfg
            .sign(&self.signing_key, &Password::Static(passwd), data)
            .map_err(Error::SignError)?;

        let mut signature_bytes = Vec::with_capacity(1024);
        let mut cursor = io::Cursor::new(&mut signature_bytes);
        signature_packet
            .to_writer_with_header(&mut cursor)
            .map_err(Error::SignError)?;

        Ok(signature_bytes)
    }
}

impl Signer {
    /// Create a signer from a bare secret key.
    ///
    /// This constructor does not retain the full key structure, so subkey selection
    /// and user ID inclusion in signatures are not available.
    /// Prefer [`Signer::from_asc`] or [`Signer::from_asc_bytes`] when possible.
    pub fn new(key: SecretKey) -> Result<Self, Error> {
        validate_algorithm(key.algorithm())?;
        Ok(Self {
            signed_keys: Vec::new(),
            signing_key: AnySigningKey::Primary(key),
            user_id: None,
            key_passphrase: None,
        })
    }

    /// Construct a [`Signer`] from an ascii armored file.
    pub fn from_asc_file(path: impl AsRef<std::path::Path>) -> Result<Self, Error> {
        let input = std::fs::read_to_string(path).map_err(Error::Io)?;
        Self::from_asc(&input)
    }

    /// Construct a [`Signer`] from ascii armored bytes.
    pub fn from_asc_bytes(input: &[u8]) -> Result<Self, Error> {
        let input = std::str::from_utf8(input).map_err(Error::KeyLoadUtf8Error)?;
        Self::from_asc(input)
    }

    /// Construct a [`Signer`] from an ascii armored string.
    ///
    /// The input may contain a single certificate or a keyring with multiple certificates.
    /// The first certificate with a supported algorithm is used.
    ///
    /// If the selected key contains a subkey with the signing capability flag, that subkey
    /// is used for signing by default. Otherwise, the primary key is used.
    /// Use [`Signer::with_signing_key`] to select a specific key by fingerprint.
    pub fn from_asc(input: &str) -> Result<Self, Error> {
        let (keys_iter, _) =
            SignedSecretKey::from_string_many(input).map_err(Error::KeyLoadSecretKeyError)?;

        let signed_keys: Vec<SignedSecretKey> = keys_iter.filter_map(|res| res.ok()).collect();

        // Find the first cert that has a usable signing key (primary or subkey
        // with a supported algorithm).
        let (signing_key, user_id) = signed_keys
            .iter()
            .find_map(|cert| {
                let user_id = cert.details.users.first().map(|u| u.id.id().to_vec());

                // Prefer the first subkey with the signing capability flag
                if let Some(sk) = cert
                    .secret_subkeys
                    .iter()
                    .find(|sk| sk.signatures.iter().any(|sig| sig.key_flags().sign()))
                    && validate_algorithm(sk.key.algorithm()).is_ok()
                {
                    return Some((AnySigningKey::Sub(sk.key.clone()), user_id));
                }

                // Fall back to the primary key
                if validate_algorithm(cert.primary_key.algorithm()).is_ok() {
                    return Some((AnySigningKey::Primary(cert.primary_key.clone()), user_id));
                }

                None
            })
            .ok_or_else(|| {
                Error::KeyLoadSecretKeyError(pgp::errors::Error::NoMatchingPacket {
                    backtrace: None,
                })
            })?;

        Ok(Self {
            signing_key,
            signed_keys,
            user_id,
            key_passphrase: None,
        })
    }

    /// Select a specific signing key by fingerprint.
    ///
    /// This matches the given fingerprint bytes against the primary keys and all secret subkeys
    /// across all certificates in the keyring. The first match is used for signing.
    ///
    /// This method is only effective when the signer was created via
    /// [`Signer::from_asc`] or [`Signer::from_asc_bytes`].
    pub fn with_signing_key(self, fingerprint: &[u8]) -> Result<Self, Error> {
        for signed_key in &self.signed_keys {
            let user_id = signed_key.details.users.first().map(|u| u.id.id().to_vec());

            // Check primary key
            if signed_key.primary_key.fingerprint().as_bytes() == fingerprint {
                validate_algorithm(signed_key.primary_key.algorithm())?;
                return Ok(Self {
                    signing_key: AnySigningKey::Primary(signed_key.primary_key.clone()),
                    user_id,
                    ..self
                });
            }

            // Check secret subkeys
            for subkey in &signed_key.secret_subkeys {
                if subkey.key.fingerprint().as_bytes() == fingerprint {
                    validate_algorithm(subkey.key.algorithm())?;
                    return Ok(Self {
                        signing_key: AnySigningKey::Sub(subkey.key.clone()),
                        user_id,
                        ..self
                    });
                }
            }
        }

        Err(Error::KeyNotFoundError {
            key_ref: hex::encode(fingerprint),
        })
    }

    /// Configures the [Signer] with the provided PGP key passphrase.
    pub fn with_key_passphrase(self, key_passphrase: impl Into<String>) -> Self {
        Self {
            key_passphrase: Some(key_passphrase.into()),
            ..self
        }
    }

    /// Prepare the configuration to sign with a given signing key
    ///
    /// This will place the expected subpackets in the object about to be signed
    /// with the underlying private key.
    fn prepare_signer_configuration<T: KeyDetails>(
        signing_key: &T,
        t: crate::Timestamp,
    ) -> Result<SignatureConfig, Error> {
        let t = pgp::types::Timestamp::from_secs(t.0);

        let hash_alg = HashAlgorithm::Sha256;
        let pub_alg = signing_key.algorithm();
        let mut sig_cfg = match signing_key.version() {
            KeyVersion::V6 => {
                let salt_len = hash_alg
                    .salt_len()
                    .expect("Sha256 always has a v6 salt length");
                let mut salt = vec![0u8; salt_len];
                getrandom::fill(&mut salt).expect("failed to generate random salt");
                SignatureConfig::v6_with_salt(SignatureType::Binary, pub_alg, hash_alg, salt)
            }
            _ => SignatureConfig::v4(SignatureType::Binary, pub_alg, hash_alg),
        };

        sig_cfg
            .hashed_subpackets
            .push(Subpacket::regular(SubpacketData::SignatureCreationTime(t))?);
        sig_cfg
            .hashed_subpackets
            .push(Subpacket::regular(SubpacketData::IssuerFingerprint(
                signing_key.fingerprint(),
            ))?);

        // v4 signatures include the legacy key ID; v6 signatures do not
        if signing_key.version() != KeyVersion::V6 {
            sig_cfg
                .hashed_subpackets
                .push(Subpacket::regular(SubpacketData::IssuerKeyId(
                    signing_key.legacy_key_id(),
                ))?);
        }

        Ok(sig_cfg)
    }
}

/// Verifier implementation using the `pgp` crate.
///
/// Supports ascii armored key files (commonly with the file extension `.asc`
/// as generated by e.g. `gpg`), including keyring files that contain multiple
/// certificates.
#[derive(Clone, Debug, Default)]
pub struct Verifier {
    public_keys: Vec<SignedPublicKey>,
}

impl Verifier {
    /// Construct a new [`Verifier`] with no keys.
    pub fn new() -> Self {
        Self::default()
    }

    pub(crate) fn parse_signature(signature: &[u8]) -> Result<pgp::packet::Signature, Error> {
        let mut cursor = io::Cursor::new(signature);
        let parser = pgp::packet::PacketParser::new(&mut cursor);
        let signature = parser
            .filter_map(|res| match res {
                Ok(::pgp::packet::Packet::Signature(sig_packet)) => Some(sig_packet),
                _ => None,
            })
            .next()
            .ok_or(Error::NoSignatureFound)?;
        let cfg = signature.config().ok_or(Error::UnknownVersionSignature)?;
        validate_algorithm(cfg.pub_alg)?;
        Ok(signature)
    }

    /// Construct a [`Verifier`] from an ascii armored file.
    pub fn from_asc_file(path: impl AsRef<std::path::Path>) -> Result<Self, Error> {
        let input = std::fs::read_to_string(path).map_err(Error::Io)?;
        Self::from_asc(&input)
    }

    /// Construct a [`Verifier`] from ascii armored bytes.
    pub fn from_asc_bytes(input: &[u8]) -> Result<Self, Error> {
        let input = std::str::from_utf8(input).map_err(Error::KeyLoadUtf8Error)?;
        Self::from_asc(input)
    }

    /// Construct a [`Verifier`] from an ascii armored string.
    ///
    /// The input may contain a single certificate or a keyring with multiple
    /// certificates. All certificates with supported algorithms are loaded.
    pub fn from_asc(input: &str) -> Result<Self, Error> {
        let mut verifier = Self::new();
        verifier.load_from_asc(input)?;
        Ok(verifier)
    }

    /// Append public key(s) from an ascii armored file.
    pub fn load_from_asc_file(&mut self, path: impl AsRef<std::path::Path>) -> Result<(), Error> {
        let input = std::fs::read_to_string(path).map_err(Error::Io)?;
        self.load_from_asc(&input)
    }

    /// Append public key(s) from ascii armored bytes.
    pub fn load_from_asc_bytes(&mut self, input: &[u8]) -> Result<(), Error> {
        let input = std::str::from_utf8(input).map_err(Error::KeyLoadUtf8Error)?;
        self.load_from_asc(input)
    }

    /// Append public key(s) from an ascii armored string.
    ///
    /// The input may contain a single certificate or a keyring with multiple
    /// certificates. All certificates with supported algorithms are appended.
    pub fn load_from_asc(&mut self, input: &str) -> Result<(), Error> {
        let (keys_iter, _) =
            SignedPublicKey::from_string_many(input).map_err(Error::KeyLoadSecretKeyError)?;

        let mut found_any = false;
        for res in keys_iter {
            if let Ok(key) = res
                && validate_algorithm(key.algorithm()).is_ok()
            {
                self.public_keys.push(key);
                found_any = true;
            }
        }

        if !found_any {
            return Err(Error::KeyLoadSecretKeyError(
                pgp::errors::Error::NoMatchingPacket { backtrace: None },
            ));
        }

        Ok(())
    }

    /// Select a specific certificate by primary key fingerprint.
    ///
    /// This filters the loaded certificates to only the one whose primary key
    /// matches the given fingerprint. Useful when a keyring contains multiple
    /// certificates and you want to verify against a specific one.
    pub fn with_key(self, fingerprint: &[u8]) -> Result<Self, Error> {
        let public_keys: Vec<SignedPublicKey> = self
            .public_keys
            .into_iter()
            .filter(|key| key.fingerprint().as_bytes() == fingerprint)
            .collect();

        if public_keys.is_empty() {
            return Err(Error::KeyNotFoundError {
                key_ref: hex::encode(fingerprint),
            });
        }

        Ok(Self { public_keys })
    }
}

impl traits::Verifying for Verifier {
    type Signature = Vec<u8>;

    fn verify(&self, mut data: impl io::Read, signature: &[u8]) -> Result<(), Error> {
        // Buffer the data so we can retry verification against multiple keys.
        let mut buf = Vec::new();
        data.read_to_end(&mut buf).map_err(Error::Io)?;

        let signature = Self::parse_signature(signature)?;
        let fingerprints = signature.issuer_fingerprint();

        if fingerprints.is_empty() {
            // No issuer fingerprint in the signature — try each primary key.
            for public_key in &self.public_keys {
                log::trace!(
                    "Signature has no issuer ref, attempting primary key: {:?}",
                    public_key.fingerprint()
                );
                if signature.verify(public_key, io::Cursor::new(&buf)).is_ok() {
                    return Ok(());
                }
            }
            return Err(Error::KeyNotFoundError {
                key_ref: "no issuer fingerprint in signature".to_string(),
            });
        }

        let mut last_err: Option<Error> = None;

        for public_key in &self.public_keys {
            for fingerprint in &fingerprints {
                log::trace!("Signature has issuer ref: {:?}", fingerprint);

                // Check primary key
                if public_key.fingerprint() == **fingerprint {
                    log::trace!(
                        "Primary key fingerprint {:?} matches signature",
                        public_key.fingerprint()
                    );
                    match signature.verify(public_key, io::Cursor::new(&buf)) {
                        Ok(_) => return Ok(()),
                        Err(source) => {
                            log::trace!("Primary key verification failed");
                            last_err = Some(Error::VerificationError {
                                source,
                                key_ref: format!("{:?}", fingerprint),
                            });
                        }
                    }
                }

                // Check subkeys
                for sub_key in &public_key.public_subkeys {
                    if sub_key.fingerprint() == **fingerprint {
                        log::trace!(
                            "Subkey fingerprint {:?} matches signature",
                            sub_key.fingerprint()
                        );
                        match signature.verify(sub_key, io::Cursor::new(&buf)) {
                            Ok(_) => return Ok(()),
                            Err(source) => {
                                log::trace!("Subkey verification failed");
                                last_err = Some(Error::VerificationError {
                                    source,
                                    key_ref: format!("{:?}", sub_key.fingerprint()),
                                });
                            }
                        }
                    }
                }
            }
        }

        Err(last_err.unwrap_or_else(|| Error::KeyNotFoundError {
            key_ref: "no matching key found".to_string(),
        }))
    }
}

/// Adapter that bridges a [`pgp::SigningKey`] implementation to the
/// rpm-rs [`Signing`](traits::Signing) trait.
///
/// This is useful when the signing key is not a local key file — for
/// example an HSM-backed key, a cloud KMS key, or any custom
/// [`pgp::SigningKey`] implementation.
///
/// The [`pgp::adapter`] module provides ready-made `SigningKey`
/// implementations — [`RsaSigner`](pgp::adapter::RsaSigner) and
/// [`EcdsaSigner`](pgp::adapter::EcdsaSigner) — that wrap any Rust
/// Crypto [`signature::Signer`], making it straightforward to plug in
/// key backends such as PKCS#11 tokens or cloud KMS clients.
///
/// See `examples/hsm-signing.rs` for a complete example.
pub struct BasicKeySigner<T> {
    secret_key: T,
}

/// Deprecated alias for [`BasicKeySigner`].
#[deprecated(since = "0.21.0", note = "renamed to `BasicKeySigner`")]
pub type HsmSigner<T> = BasicKeySigner<T>;

impl<T> BasicKeySigner<T> {
    /// Create a new [`BasicKeySigner`] with the underlying `secret_key`
    pub fn new(secret_key: T) -> Self {
        Self { secret_key }
    }
}

impl<T> fmt::Debug for BasicKeySigner<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("BasicKeySigner").finish_non_exhaustive()
    }
}

impl<T> traits::Signing for BasicKeySigner<T>
where
    T: KeyDetails + SigningKey,
{
    type Signature = Vec<u8>;

    fn sign(&self, data: impl io::Read, t: crate::Timestamp) -> Result<Self::Signature, Error> {
        let sig_cfg = Signer::prepare_signer_configuration(&self.secret_key, t)?;

        let signature_packet = sig_cfg
            .sign(&self.secret_key, &Password::empty(), data)
            .map_err(Error::SignError)?;

        let mut signature_bytes = Vec::with_capacity(1024);
        let mut cursor = io::Cursor::new(&mut signature_bytes);
        signature_packet
            .to_writer_with_header(&mut cursor)
            .map_err(Error::SignError)?;

        Ok(signature_bytes)
    }
}

/// The public key algorithm used in an OpenPGP signature.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum SignatureAlgorithm {
    RSA,
    DSA,
    ECDSA,
    EdDSALegacy,
    Ed25519,
    Ed448,
    MlDsa65Ed25519,
    MlDsa87Ed448,
    /// An algorithm not recognized for use signing RPMs.
    Unsupported(u8),
}

impl From<PublicKeyAlgorithm> for SignatureAlgorithm {
    fn from(alg: PublicKeyAlgorithm) -> Self {
        match alg {
            PublicKeyAlgorithm::RSA | PublicKeyAlgorithm::RSASign => Self::RSA,
            PublicKeyAlgorithm::DSA => Self::DSA,
            PublicKeyAlgorithm::ECDSA => Self::ECDSA,
            PublicKeyAlgorithm::EdDSALegacy => Self::EdDSALegacy,
            PublicKeyAlgorithm::Ed25519 => Self::Ed25519,
            PublicKeyAlgorithm::Ed448 => Self::Ed448,
            PublicKeyAlgorithm::MlDsa65Ed25519 => Self::MlDsa65Ed25519,
            PublicKeyAlgorithm::MlDsa87Ed448 => Self::MlDsa87Ed448,
            other => Self::Unsupported(other.into()),
        }
    }
}

/// The hash algorithm used in an OpenPGP signature.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum SignatureHashAlgorithm {
    SHA1,
    SHA256,
    SHA384,
    SHA512,
    SHA224,
    SHA3_256,
    SHA3_512,
    /// A hash algorithm not recognized by this library.
    Unsupported(u8),
}

impl From<HashAlgorithm> for SignatureHashAlgorithm {
    fn from(alg: HashAlgorithm) -> Self {
        match alg {
            HashAlgorithm::Sha1 => Self::SHA1,
            HashAlgorithm::Sha256 => Self::SHA256,
            HashAlgorithm::Sha384 => Self::SHA384,
            HashAlgorithm::Sha512 => Self::SHA512,
            HashAlgorithm::Sha224 => Self::SHA224,
            HashAlgorithm::Sha3_256 => Self::SHA3_256,
            HashAlgorithm::Sha3_512 => Self::SHA3_512,
            other => Self::Unsupported(other.into()),
        }
    }
}

/// The version of an OpenPGP signature packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum SignatureVersion {
    V4,
    V6,
    /// A version not recognized by this library.
    Unsupported(u8),
}

impl From<u8> for SignatureVersion {
    fn from(v: u8) -> Self {
        match v {
            4 => Self::V4,
            6 => Self::V6,
            other => Self::Unsupported(other),
        }
    }
}

/// Parsed information about a single OpenPGP signature embedded in an RPM package.
///
/// This provides access to the issuer fingerprint, key ID, algorithm, and creation time
/// without exposing the underlying PGP library types.
#[derive(Debug, Clone)]
pub struct SignatureInfo {
    fingerprint: Option<String>,
    key_id: Option<String>,
    version: SignatureVersion,
    algorithm: Option<SignatureAlgorithm>,
    hash_algorithm: Option<SignatureHashAlgorithm>,
    created: Option<u32>,
}

impl SignatureInfo {
    pub(crate) fn from_pgp_signature(sig: &pgp::packet::Signature) -> Self {
        let fingerprint = sig.issuer_fingerprint().first().map(|fp| format!("{fp:x}"));
        let key_id = sig.issuer_key_id().first().map(|kid| format!("{kid}"));
        let version: SignatureVersion = Into::<u8>::into(sig.version()).into();
        let algorithm = sig.config().map(|c| c.pub_alg.into());
        let hash_algorithm = sig.hash_alg().map(|h| h.into());
        let created = sig.created().map(|t| t.as_secs());

        Self {
            fingerprint,
            key_id,
            version,
            algorithm,
            hash_algorithm,
            created,
        }
    }

    /// The issuer fingerprint as a lowercase hex string, if present.
    ///
    /// This is always available for v4 and v6 OpenPGP signatures.
    pub fn fingerprint(&self) -> Option<&str> {
        self.fingerprint.as_deref()
    }

    /// The issuer key ID as a lowercase hex string, if present.
    ///
    /// This is typically available for v4 OpenPGP signatures but not for v6,
    /// which only use issuer fingerprint subpackets.
    pub fn key_id(&self) -> Option<&str> {
        self.key_id.as_deref()
    }

    /// The OpenPGP signature packet version (e.g. 4 or 6).
    pub fn version(&self) -> SignatureVersion {
        self.version
    }

    /// The public key algorithm used to create the signature, if known.
    pub fn algorithm(&self) -> Option<SignatureAlgorithm> {
        self.algorithm
    }

    /// The hash algorithm used in the signature, if known.
    pub fn hash_algorithm(&self) -> Option<SignatureHashAlgorithm> {
        self.hash_algorithm
    }

    /// The signature creation time as seconds since the Unix epoch, if present.
    pub fn created(&self) -> Option<u32> {
        self.created
    }
}

#[cfg(test)]
pub(crate) mod test {
    use super::*;
    use crate::signature::pgp::{Signer, Verifier};
    use crate::signature::{Signing, Verifying, echo_signature};
    use std::io::Cursor;

    const TEST_DATA: &[u8] = b"dfsdfjsd9ivnq320348934752312308205723900000580134850sdf";
    const TEST_TIMESTAMP: crate::Timestamp = crate::Timestamp(1_600_000_000);

    fn sign_verify_roundtrip(signer: &Signer, verifier: &Verifier) {
        let mut cursor = Cursor::new(TEST_DATA);

        let signature = signer.sign(&mut cursor, TEST_TIMESTAMP).expect("signed");
        let signature = signature.as_slice();

        Verifier::parse_signature(signature).expect("Created signature should be parsable");
        echo_signature("test/roundtrip", signature);

        let mut cursor = Cursor::new(TEST_DATA);
        verifier
            .verify(&mut cursor, signature)
            .expect("failed to verify just signed signature");
    }

    mod basic_key_signer {
        use super::*;
        use pgp::adapter::RsaSigner;
        use pgp::types::KeyVersion;
        use rsa::{RsaPrivateKey, pkcs1v15};

        fn prep_rsa() -> BasicKeySigner<RsaSigner<pkcs1v15::SigningKey<sha2::Sha256>, sha2::Sha256>>
        {
            let rsa_key = RsaPrivateKey::new(&mut rsa::rand_core::OsRng, 2048)
                .expect("failed to generate RSA key");
            let rsa_key = pkcs1v15::SigningKey::<sha2::Sha256>::new(rsa_key);

            let rsa_signer = RsaSigner::new(
                rsa_key,
                KeyVersion::V4,
                pgp::types::Timestamp::from_secs(TEST_TIMESTAMP.0),
            )
            .expect("create PGP signer");

            BasicKeySigner::new(rsa_signer)
        }

        #[test]
        fn sign_produces_parseable_signature() {
            let signer = prep_rsa();
            let signature = signer
                .sign(Cursor::new(TEST_DATA), TEST_TIMESTAMP)
                .expect("signing should succeed");
            Verifier::parse_signature(&signature).expect("signature should be parseable");
        }

        #[test]
        fn sign_and_verify_with_signer_key() {
            let signing_key = include_bytes!(
                "../../../tests/assets/signing_keys/v4/rpm-testkey-v4-rsa4096.secret"
            );
            let verification_key =
                include_bytes!("../../../tests/assets/signing_keys/v4/rpm-testkey-v4-rsa4096.asc");

            let signer = Signer::from_asc_bytes(signing_key.as_slice()).expect("SK parsing failed");
            let verifier =
                Verifier::from_asc_bytes(verification_key.as_slice()).expect("PK parsing failed");

            // Use the Signer's internals to construct a BasicKeySigner
            let basic_signer = BasicKeySigner::new(signer.signing_key.clone());

            let signature = basic_signer
                .sign(Cursor::new(TEST_DATA), TEST_TIMESTAMP)
                .expect("signing should succeed");

            Verifier::parse_signature(&signature).expect("signature should be parseable");

            verifier
                .verify(Cursor::new(TEST_DATA), &signature)
                .expect("verification should succeed");
        }
    }

    mod v4 {
        use super::*;

        fn prep() -> (Signer, Verifier) {
            let _ = env_logger::try_init();
            let signing_key = include_bytes!(
                "../../../tests/assets/signing_keys/v4/rpm-testkey-v4-rsa4096.secret"
            );
            let verification_key =
                include_bytes!("../../../tests/assets/signing_keys/v4/rpm-testkey-v4-rsa4096.asc");
            let verifier =
                Verifier::from_asc_bytes(verification_key.as_slice()).expect("PK parsing failed");
            let signer = Signer::from_asc_bytes(signing_key.as_slice()).expect("SK parsing failed");
            (signer, verifier)
        }

        /// Sign data with a v4 RSA key and verify the signature through
        /// our public Signer/Verifier API.
        #[test]
        fn sign_verify_roundtrip() {
            let (signer, verifier) = prep();
            super::sign_verify_roundtrip(&signer, &verifier);
        }

        /// Verify that `from_asc` uses the primary key when there
        /// are no subkeys (the typical v4 case).
        #[test]
        fn uses_primary_key_without_subkeys() {
            let (signer, _verifier) = prep();
            assert!(
                matches!(signer.signing_key, AnySigningKey::Primary(_)),
                "v4 key without subkeys should use the primary key"
            );
        }
    }

    mod v6 {
        use super::*;

        fn prep() -> (Signer, Verifier) {
            let _ = env_logger::try_init();
            let signing_key = include_bytes!(
                "../../../tests/assets/signing_keys/v6/rpm-testkey-v6-ed25519.secret"
            );
            let verification_key =
                include_bytes!("../../../tests/assets/signing_keys/v6/rpm-testkey-v6-ed25519.asc");
            let verifier =
                Verifier::from_asc_bytes(verification_key.as_slice()).expect("PK parsing failed");
            let signer = Signer::from_asc_bytes(signing_key.as_slice()).expect("SK parsing failed");
            (signer, verifier)
        }

        /// Sign data with a v6 Ed25519 key and verify the signature through
        /// our public Signer/Verifier API.
        #[test]
        fn sign_verify_roundtrip() {
            let (signer, verifier) = prep();
            super::sign_verify_roundtrip(&signer, &verifier);
        }

        /// Verify that `load_from_asc` auto-selects the signing subkey for
        /// v6 keys where the primary key is certification-only.
        #[test]
        fn auto_selects_signing_subkey() {
            let (signer, _verifier) = prep();
            assert!(
                matches!(signer.signing_key, AnySigningKey::Sub(_)),
                "v6 key with a signing subkey should auto-select it"
            );
        }

        /// Explicitly select the primary key via `with_signing_key` and verify
        /// the result is equivalent to the default behavior.
        #[test]
        fn with_signing_key_primary() {
            let (signer, verifier) = prep();

            let signed_key = signer.signed_keys.first().unwrap();
            let primary_fingerprint = signed_key.primary_key.fingerprint();

            let signer = signer
                .with_signing_key(primary_fingerprint.as_bytes())
                .expect("primary key selection should succeed");

            assert!(
                matches!(signer.signing_key, AnySigningKey::Primary(_)),
                "should be using the primary key"
            );

            super::sign_verify_roundtrip(&signer, &verifier);
        }

        /// Verify that `with_signing_key` returns an error when given a fingerprint that
        /// doesn't match any key in the key material.
        #[test]
        fn with_signing_key_not_found() {
            let (signer, _verifier) = prep();
            let bogus_fingerprint = [0xDE, 0xAD, 0xBE, 0xEF];
            let result = signer.with_signing_key(&bogus_fingerprint);
            assert!(result.is_err(), "should fail with unknown fingerprint");
        }

        /// Verify that signatures include the `SignersUserID` subpacket when the key
        /// material contains a user ID.
        #[test]
        fn user_id_included_in_signature() {
            let (signer, _verifier) = prep();

            assert!(
                signer.user_id.is_some(),
                "user_id should be populated from the key"
            );

            let signature = signer
                .sign(Cursor::new(TEST_DATA), TEST_TIMESTAMP)
                .expect("signing should succeed");

            let parsed = Verifier::parse_signature(&signature).expect("should parse");
            let config = parsed.config().expect("should have config");
            let has_signer_uid = config
                .hashed_subpackets
                .iter()
                .any(|sp| matches!(sp.data, SubpacketData::SignersUserID(_)));
            assert!(
                has_signer_uid,
                "signature should contain SignersUserID subpacket"
            );
        }
    }

    mod keyring {
        use super::*;

        fn prep_keyring_signer() -> Signer {
            let _ = env_logger::try_init();
            let keyring = include_bytes!(
                "../../../tests/assets/signing_keys/v4/rpm-testkey-v4-keyring.secret"
            );
            Signer::from_asc_bytes(keyring.as_slice()).expect("keyring parsing failed")
        }

        /// Verify that `with_signing_key` updates user_id to match the certificate
        /// that owns the selected key.
        #[test]
        fn with_signing_key_updates_user_id() {
            let signer = prep_keyring_signer();
            let original_user_id = signer.user_id.clone();

            // Find a different cert in the keyring
            let other_cert = signer
                .signed_keys
                .iter()
                .find(|sk| sk.details.users.first().map(|u| u.id.id().to_vec()) != original_user_id)
                .expect("keyring should contain multiple certs with different user IDs");

            let other_user_id = other_cert.details.users.first().map(|u| u.id.id().to_vec());
            let other_fingerprint = other_cert.primary_key.fingerprint();

            let switched_signer = signer
                .with_signing_key(other_fingerprint.as_bytes())
                .expect("key selection should succeed");

            assert_eq!(
                switched_signer.user_id, other_user_id,
                "user_id should match the selected key's certificate"
            );
            assert_ne!(
                switched_signer.user_id, original_user_id,
                "user_id should have changed from the original"
            );
        }

        /// Verify that the SignersUserID subpacket in the signature matches the certificate
        /// selected via `with_signing_key`.
        #[test]
        fn with_signing_key_signature_contains_correct_user_id() {
            const PASSPHRASE: &str = "thisisN0Tasecuredpassphrase";
            let signer = prep_keyring_signer();

            for signed_key in &signer.signed_keys {
                let expected_uid = signed_key.details.users.first().map(|u| u.id.id().to_vec());
                let fpr = signed_key.primary_key.fingerprint();

                let selected_signer = signer
                    .clone()
                    .with_signing_key(fpr.as_bytes())
                    .expect("key selection should succeed")
                    .with_key_passphrase(PASSPHRASE);

                let signature = selected_signer
                    .sign(Cursor::new(TEST_DATA), TEST_TIMESTAMP)
                    .expect("signing should succeed");

                let parsed = Verifier::parse_signature(&signature).expect("should parse");
                let config = parsed.config().expect("should have config");
                let sig_uid = config
                    .hashed_subpackets
                    .iter()
                    .find_map(|sp| match &sp.data {
                        SubpacketData::SignersUserID(uid) => Some(uid.as_ref().to_vec()),
                        _ => None,
                    });

                assert_eq!(
                    sig_uid, expected_uid,
                    "signature should contain the user ID from the selected key's certificate"
                );
            }
        }
    }
}
