use super::{AlgorithmType, traits};
use crate::errors::Error;

use std::io;
use zeroize::Zeroizing;

use pgp::{
    composed::{Deserializable, SignedPublicKey, SignedSecretKey},
    crypto::{hash::HashAlgorithm, public_key::PublicKeyAlgorithm},
    packet::{
        PacketTrait, SecretKey, SecretSubkey, SignatureConfig, SignatureType, Subpacket,
        SubpacketData,
    },
    types::{KeyDetails, KeyVersion, Password, PublicParams, SigningKey},
};

/// An enum that can hold either a primary key or a subkey for signing.
#[derive(Clone, Debug)]
enum AnySigningKey {
    Primary(SecretKey),
    Sub(SecretSubkey),
}

macro_rules! delegate_any_signing_key {
    ($self:expr, $method:ident $(, $arg:expr)*) => {
        match $self {
            AnySigningKey::Primary(k) => k.$method($($arg),*),
            AnySigningKey::Sub(k) => k.$method($($arg),*),
        }
    };
}

impl KeyDetails for AnySigningKey {
    fn version(&self) -> KeyVersion {
        delegate_any_signing_key!(self, version)
    }

    fn legacy_key_id(&self) -> pgp::types::KeyId {
        delegate_any_signing_key!(self, legacy_key_id)
    }

    fn fingerprint(&self) -> pgp::types::Fingerprint {
        delegate_any_signing_key!(self, fingerprint)
    }

    fn algorithm(&self) -> PublicKeyAlgorithm {
        delegate_any_signing_key!(self, algorithm)
    }

    fn created_at(&self) -> pgp::types::Timestamp {
        delegate_any_signing_key!(self, created_at)
    }

    fn legacy_v3_expiration_days(&self) -> Option<u16> {
        delegate_any_signing_key!(self, legacy_v3_expiration_days)
    }

    fn public_params(&self) -> &PublicParams {
        delegate_any_signing_key!(self, public_params)
    }
}

impl SigningKey for AnySigningKey {
    fn sign(
        &self,
        passwd: &Password,
        hash_alg: HashAlgorithm,
        digest: &[u8],
    ) -> pgp::errors::Result<pgp::types::SignatureBytes> {
        match self {
            Self::Primary(k) => SigningKey::sign(k, passwd, hash_alg, digest),
            Self::Sub(k) => SigningKey::sign(k, passwd, hash_alg, digest),
        }
    }

    fn hash_alg(&self) -> HashAlgorithm {
        delegate_any_signing_key!(self, hash_alg)
    }
}

fn algorithm_type(alg: PublicKeyAlgorithm) -> Result<AlgorithmType, Error> {
    match alg {
        PublicKeyAlgorithm::RSA => Ok(AlgorithmType::RSA),
        PublicKeyAlgorithm::EdDSALegacy | PublicKeyAlgorithm::Ed25519 => Ok(AlgorithmType::EdDSA),
        PublicKeyAlgorithm::ECDSA => Ok(AlgorithmType::ECDSA),
        algorithm => Err(Error::UnsupportedPGPKeyType(algorithm)),
    }
}

impl From<traits::AlgorithmType> for ::pgp::crypto::public_key::PublicKeyAlgorithm {
    fn from(value: traits::AlgorithmType) -> Self {
        match value {
            traits::AlgorithmType::RSA => PublicKeyAlgorithm::RSA,
            traits::AlgorithmType::EdDSA => PublicKeyAlgorithm::EdDSALegacy,
            traits::AlgorithmType::ECDSA => PublicKeyAlgorithm::ECDSA,
        }
    }
}

/// Signer implementation using the `pgp` crate.
///
/// This supports either ascii armored key files (commonly with
/// the file extension `.asc` as generated by i.e. `gpg`.), or
/// bare key objects via [`Signer::new`].
///
/// When loaded from an ascii armored key, the signer retains the full key
/// structure, enabling subkey selection via [`Signer::with_signing_key`]
/// and automatic inclusion of the signer's user ID in signatures.
#[derive(Clone, Debug)]
pub struct Signer {
    /// The full signed key, if available (from load_from_asc).
    signed_key: Option<SignedSecretKey>,
    /// The actual key used for signing (primary or selected subkey).
    signing_key: AnySigningKey,
    /// The signer's user ID, included in signatures when available.
    user_id: Option<Vec<u8>>,
    algorithm: traits::AlgorithmType,
    key_passphrase: Option<String>,
}

impl traits::Signing for Signer {
    type Signature = Vec<u8>;

    fn sign(&self, data: impl io::Read, t: crate::Timestamp) -> Result<Self::Signature, Error> {
        let t = pgp::types::Timestamp::from_secs(t.0);

        let hash_alg = HashAlgorithm::Sha256;
        let pub_alg = self.signing_key.algorithm();
        let mut sig_cfg = match self.signing_key.version() {
            KeyVersion::V6 => {
                let salt_len = hash_alg
                    .salt_len()
                    .expect("Sha256 always has a v6 salt length");
                let mut salt = vec![0u8; salt_len];
                getrandom::getrandom(&mut salt).expect("failed to generate random salt");
                SignatureConfig::v6_with_salt(SignatureType::Binary, pub_alg, hash_alg, salt)
            }
            _ => SignatureConfig::v4(SignatureType::Binary, pub_alg, hash_alg),
        };

        sig_cfg
            .hashed_subpackets
            .push(Subpacket::regular(SubpacketData::SignatureCreationTime(t))?);
        sig_cfg
            .hashed_subpackets
            .push(Subpacket::regular(SubpacketData::IssuerFingerprint(
                self.signing_key.fingerprint(),
            ))?);

        // v4 signatures include the legacy key ID; v6 signatures do not
        if self.signing_key.version() != KeyVersion::V6 {
            sig_cfg
                .hashed_subpackets
                .push(Subpacket::regular(SubpacketData::IssuerKeyId(
                    self.signing_key.legacy_key_id(),
                ))?);
        }

        if let Some(ref uid) = self.user_id {
            sig_cfg
                .hashed_subpackets
                .push(Subpacket::regular(SubpacketData::SignersUserID(
                    uid.clone().into(),
                ))?);
        }

        let pw = self.key_passphrase.clone().unwrap_or_default();
        let passwd = Zeroizing::new(pw.into());

        let signature_packet = sig_cfg
            .sign(&self.signing_key, &Password::Static(passwd), data)
            .map_err(Error::SignError)?;

        let mut signature_bytes = Vec::with_capacity(1024);
        let mut cursor = io::Cursor::new(&mut signature_bytes);
        signature_packet
            .to_writer_with_header(&mut cursor)
            .map_err(Error::SignError)?;

        Ok(signature_bytes)
    }

    fn algorithm(&self) -> traits::AlgorithmType {
        self.algorithm
    }
}

impl Signer {
    /// Create a signer from a bare secret key.
    ///
    /// This constructor does not retain the full key structure, so subkey
    /// selection and user ID inclusion in signatures are not available.
    /// Prefer [`Signer::load_from_asc`] or [`Signer::load_from_asc_bytes`]
    /// when possible.
    pub fn new(key: SecretKey) -> Result<Self, Error> {
        let algorithm = algorithm_type(key.algorithm())?;
        Ok(Self {
            signed_key: None,
            signing_key: AnySigningKey::Primary(key),
            user_id: None,
            algorithm,
            key_passphrase: None,
        })
    }

    /// Load the private key for signing from ascii armored bytes.
    pub fn load_from_asc_bytes(input: &[u8]) -> Result<Self, Error> {
        let input = std::str::from_utf8(input).map_err(Error::KeyLoadUtf8Error)?;
        Self::load_from_asc(input)
    }

    /// Load the private key for signing from an ascii armored string.
    ///
    /// The primary key is used for signing by default. Use
    /// [`Signer::with_signing_key`] to select a specific subkey instead.
    pub fn load_from_asc(input: &str) -> Result<Self, Error> {
        let (signed_key, _) =
            SignedSecretKey::from_string(input).map_err(Error::KeyLoadSecretKeyError)?;

        let user_id = signed_key
            .details
            .users
            .first()
            .map(|u| u.id.id().to_vec());

        let algorithm = algorithm_type(signed_key.primary_key.algorithm())?;

        Ok(Self {
            signing_key: AnySigningKey::Primary(signed_key.primary_key.clone()),
            signed_key: Some(signed_key),
            user_id,
            algorithm,
            key_passphrase: None,
        })
    }

    /// Select a specific signing key by fingerprint.
    ///
    /// This matches the given fingerprint bytes against the primary key and
    /// all secret subkeys. The first match is used for signing.
    ///
    /// This method is only effective when the signer was created via
    /// [`Signer::load_from_asc`] or [`Signer::load_from_asc_bytes`].
    pub fn with_signing_key(self, fingerprint: &[u8]) -> Result<Self, Error> {
        let signed_key = self.signed_key.as_ref().ok_or_else(|| Error::KeyNotFoundError {
            key_ref: hex::encode(fingerprint),
        })?;

        // Check primary key
        if signed_key.primary_key.fingerprint().as_bytes() == fingerprint {
            let algorithm = algorithm_type(signed_key.primary_key.algorithm())?;
            return Ok(Self {
                signing_key: AnySigningKey::Primary(signed_key.primary_key.clone()),
                algorithm,
                ..self
            });
        }

        // Check secret subkeys
        for subkey in &signed_key.secret_subkeys {
            if subkey.key.fingerprint().as_bytes() == fingerprint {
                let algorithm = algorithm_type(subkey.key.algorithm())?;
                return Ok(Self {
                    signing_key: AnySigningKey::Sub(subkey.key.clone()),
                    algorithm,
                    ..self
                });
            }
        }

        Err(Error::KeyNotFoundError {
            key_ref: hex::encode(fingerprint),
        })
    }

    /// Configures the [Signer] with the provided PGP key passphrase.
    pub fn with_key_passphrase(self, key_passphrase: impl Into<String>) -> Self {
        Self {
            key_passphrase: Some(key_passphrase.into()),
            ..self
        }
    }
}

/// Verifier implementation using the `pgp` crate.
///
/// Note that this only supports ascii armored key files
/// commonly with the file extension `.asc` as generated
/// by i.e. `gpg`.
#[derive(Clone, Debug)]
pub struct Verifier {
    public_key: SignedPublicKey,
    algorithm: AlgorithmType,
}

impl Verifier {
    pub(crate) fn parse_signature(signature: &[u8]) -> Result<pgp::packet::Signature, Error> {
        let mut cursor = io::Cursor::new(signature);
        let parser = pgp::packet::PacketParser::new(&mut cursor);
        let signature = parser
            .filter_map(|res| match res {
                Ok(::pgp::packet::Packet::Signature(sig_packet)) => Some(sig_packet),
                _ => None,
            })
            .next()
            .ok_or(Error::NoSignatureFound)?;
        Ok(signature)
    }
}

impl traits::Verifying for Verifier {
    type Signature = Vec<u8>;
    /// Despite the fact the API suggest zero copy pattern,
    /// it internally creates a copy until crate `pgp` provides
    /// a `Read` based implementation.
    fn verify(&self, mut data: impl io::Read, signature: &[u8]) -> Result<(), Error> {
        let signature = Self::parse_signature(signature)?;

        let fingerprints = signature.issuer_fingerprint();
        if fingerprints.is_empty() {
            log::trace!(
                "Signature has no issuer ref, attempting primary key: {:?}",
                self.public_key.fingerprint()
            );
            signature
                .verify(&self.public_key, data)
                .map_err(|source| Error::VerificationError {
                    source,
                    key_ref: format!("{:?}", self.public_key.fingerprint()),
                })
        } else {
            let mut result: Option<Error> = None;
            for fingerprint in fingerprints {
                log::trace!("Signature has issuer ref: {:?}", fingerprint);
                if self.public_key.fingerprint() == *fingerprint {
                    return signature.verify(&self.public_key, data).map_err(|source| {
                        Error::VerificationError {
                            source,
                            key_ref: format!("{:?}", fingerprint),
                        }
                    });
                } else {
                    log::trace!(
                        "Signature issuer fingerprint {:?} does not match primary key fingerprint: {:?}",
                        fingerprint,
                        self.public_key.fingerprint()
                    );
                }

                for sub_key in &self.public_key.public_subkeys {
                    log::trace!("Trying subkey candidate {:?}", sub_key.fingerprint());

                    if sub_key.fingerprint() == *fingerprint {
                        log::trace!(
                            "Subkey fingerprint {:?} matches signature fingerprint",
                            sub_key.fingerprint()
                        );

                        match signature.verify(sub_key, &mut data) {
                            Ok(_) => {
                                log::trace!(
                                    "Signature successfully verified with subkey {:?}",
                                    sub_key.fingerprint()
                                );
                                return Ok(());
                            }
                            Err(source) => {
                                log::trace!("Subkey verification failed");
                                result = Some(Error::VerificationError {
                                    source,
                                    key_ref: format!("{:?}", sub_key.fingerprint()),
                                })
                            }
                        }
                    } else {
                        log::trace!(
                            "Subkey fingerprint {:?} does not match signature",
                            sub_key.fingerprint()
                        );
                    }
                }
            }
            let default_err = Error::KeyNotFoundError {
                key_ref: format!("{:?}", self.public_key.fingerprint()),
            };

            match result {
                Some(err) => Err(err),
                _ => Err(default_err),
            }
        }
    }

    fn algorithm(&self) -> super::AlgorithmType {
        self.algorithm
    }
}

impl Verifier {
    pub fn load_from_asc_bytes(input: &[u8]) -> Result<Self, Error> {
        // only asc loading is supported right now
        let input = std::str::from_utf8(input).map_err(Error::KeyLoadUtf8Error)?;
        Self::load_from_asc(input)
    }

    pub fn load_from_asc(input: &str) -> Result<Self, Error> {
        let (public_key, _) =
            SignedPublicKey::from_string(input).map_err(Error::KeyLoadSecretKeyError)?;

        match public_key.algorithm() {
            PublicKeyAlgorithm::RSA => Ok(Self {
                public_key,
                algorithm: AlgorithmType::RSA,
            }),
            PublicKeyAlgorithm::EdDSALegacy | PublicKeyAlgorithm::Ed25519 => Ok(Self {
                public_key,
                algorithm: AlgorithmType::EdDSA,
            }),
            PublicKeyAlgorithm::ECDSA => Ok(Self {
                public_key,
                algorithm: AlgorithmType::ECDSA,
            }),
            a => Err(Error::UnsupportedPGPKeyType(a)),
        }
    }
}

#[cfg(test)]
pub(crate) mod test {
    use super::*;
    use crate::signature::pgp::{Signer, Verifier};
    use crate::signature::{Signing, Verifying, echo_signature};
    use hex_literal::hex;
    use std::io::Cursor;

    const TEST_DATA: &[u8] = b"dfsdfjsd9ivnq320348934752312308205723900000580134850sdf";
    const TEST_TIMESTAMP: crate::Timestamp = crate::Timestamp(1_600_000_000);

    fn sign_verify_roundtrip(signer: &Signer, verifier: &Verifier) {
        let mut cursor = Cursor::new(TEST_DATA);

        let signature = signer.sign(&mut cursor, TEST_TIMESTAMP).expect("signed");
        let signature = signature.as_slice();

        Verifier::parse_signature(signature).expect("Created signature should be parsable");
        echo_signature("test/roundtrip", signature);

        let mut cursor = Cursor::new(TEST_DATA);
        verifier
            .verify(&mut cursor, signature)
            .expect("failed to verify just signed signature");
    }

    mod v4 {
        use super::*;

        fn prep() -> (Signer, Verifier) {
            let _ = env_logger::try_init();
            let signing_key = include_bytes!(
                "../../../tests/assets/signing_keys/v4/rpm-testkey-v4-rsa4096.secret"
            );
            let verification_key =
                include_bytes!("../../../tests/assets/signing_keys/v4/rpm-testkey-v4-rsa4096.asc");
            let verifier = Verifier::load_from_asc_bytes(verification_key.as_slice())
                .expect("PK parsing failed");
            let signer =
                Signer::load_from_asc_bytes(signing_key.as_slice()).expect("SK parsing failed");
            (signer, verifier)
        }

        #[test]
        fn sign_verify_roundtrip() {
            let (signer, verifier) = prep();
            super::sign_verify_roundtrip(&signer, &verifier);
        }

        #[test]
        fn sign_and_verify_via_pgp_crate() {
            use pgp::packet::Signature;
            use pgp::types::{SigningKey, VerifyingKey};

            const RPM_SHA2_256: [u8; 32] =
                hex!("d92bfe276e311a67fe128768c5df4d06fd461e043afdf872ba4c679d860db81e");

            let (signer, verifier) = prep();
            let signing_key = match signer.signing_key {
                AnySigningKey::Primary(k) => k,
                _ => unreachable!(),
            };
            let verification_key = verifier.public_key;

            let passwd = Password::empty();
            let digest = &RPM_SHA2_256[..];

            // stage 1: verify created signature is fine
            let signature = signing_key
                .sign(&passwd, HashAlgorithm::Sha256, digest)
                .expect("Failed to create signature");

            verification_key
                .verify(HashAlgorithm::Sha256, digest, &signature)
                .expect("Failed to validate signature");

            // stage 2: check parsing success
            let sig_time = pgp::types::Timestamp::from_secs(TEST_TIMESTAMP.0);
            let packet_header = pgp::packet::PacketHeader::from_parts(
                pgp::types::PacketHeaderVersion::Old,
                pgp::types::Tag::Signature,
                pgp::types::PacketLength::Fixed(540),
            )
            .unwrap();
            let wrapped = Signature::v4(
                packet_header,
                SignatureType::Binary,
                PublicKeyAlgorithm::RSA,
                HashAlgorithm::Sha256,
                [digest[0], digest[1]],
                signature,
                vec![
                    Subpacket::regular(SubpacketData::SignatureCreationTime(sig_time)).unwrap(),
                    Subpacket::regular(SubpacketData::IssuerKeyId(signing_key.legacy_key_id()))
                        .unwrap(),
                ],
                vec![],
            );

            let mut x = Vec::with_capacity(1024);
            let mut buff = Cursor::new(&mut x);
            wrapped
                .to_writer_with_header(&mut buff)
                .expect("Write should be ok");

            let signature =
                Verifier::parse_signature(x.as_slice()).expect("There is a signature for sure");
            assert_eq!(signature, wrapped);
            let signature = signature.signature().unwrap();
            verification_key
                .verify(HashAlgorithm::Sha256, digest, &signature)
                .expect("Verify must succeed");
        }

        #[test]
        fn sign_config_and_verify_via_pgp_crate() {
            let (signer, verifier) = prep();

            let data = [1u8; 322];
            let data = &data[..];

            let passwd = Password::empty();
            let sig_time = pgp::types::Timestamp::from_secs(TEST_TIMESTAMP.0);

            let mut sig_cfg = SignatureConfig::v4(
                SignatureType::Binary,
                PublicKeyAlgorithm::RSA,
                HashAlgorithm::Sha256,
            );
            sig_cfg.hashed_subpackets.push(
                Subpacket::regular(SubpacketData::SignatureCreationTime(sig_time)).unwrap(),
            );
            sig_cfg.hashed_subpackets.push(
                Subpacket::regular(SubpacketData::IssuerKeyId(
                    signer.signing_key.legacy_key_id(),
                ))
                .unwrap(),
            );

            let signature_packet = sig_cfg
                .sign(&signer.signing_key, &passwd, data)
                .expect("Should sign");

            signature_packet
                .verify(&verifier.public_key, data)
                .expect("Failed to validate signature");
        }

        #[test]
        fn parse_static_rpm_sign_signature() {
            let _ = env_logger::try_init();

            /// A sample signature extracted from rpm-sign using the v4 RSA test keys.
            /// Should only be used for validating parsing.
            const RPM_SIGN_SIGNATURE: [u8; 536] = hex!(
                "8902150305005be98c5b24c6a8a7f4a80eb50108a84c0ffd1a9de30f7ebb74e3"
                "62effd4d1c11a168220dff4a721118e4b0466b1182c6d4d6db53641b32334195"
                "f30ca6c250ee81816a0805fa3b2666635cfa4b2502e7ad3f4f827aa34dad0da0"
                "196377d2183054c71423220b0dd8ba1b6c94b30fb382186233514eaafa848a4b"
                "cd8272f1409438c7bc48294f3298d9af351a0bf0877439d6e786449d5c7ade63"
                "1a16b2291d469e61adff916f51658ab9370e65b6772fb7746a9c8af04b2d87bf"
                "61ff70dc29ec9a0c7f12f655ea22b5f01a0da5e8c67f1b9c551b355cac722686"
                "8930d52d08930f9e1afd8c7edbca574fd942d7f674cdf668efe324669229da96"
                "878ea2882378eec3fc71fdb6366badd754554da0a3407051c276de9fa3e57f80"
                "72a9c37f3e37d77a9998c4c64b5193bcd0f29309737f6e7ab46b7b79e0455539"
                "fc61a7dea5ff80313914f6b6076cd7a410a087554de5a526c1990e5819aec3bf"
                "e81648e08596511872b80f009f26deec1232ecd03cde310bd6bf4ac5665ccdb0"
                "293c6dc61856d717b44debdcbbe44f1af5723a96444df314b17975a46acc9d27"
                "47a912a707a830aef2debc3387b58c053f454e644a866dc3f4fe059181952fad"
                "81da1b39f8f0b846f03882a6f235344d9e179a97afbd9b193188d83a502e9150"
                "45059288b207109a6c44a2720fca6817991a62cd66230f90a414a66c7d06c44b"
                "be814772ebd4a23d637386ef0e2b78d44f482eb0558c8e5d"
            );

            Verifier::parse_signature(&RPM_SIGN_SIGNATURE).expect("It should load");
        }
    }

    mod v6 {
        use super::*;

        fn prep() -> (Signer, Verifier) {
            let _ = env_logger::try_init();
            let signing_key = include_bytes!(
                "../../../tests/assets/signing_keys/v6/rpm-testkey-v6-ed25519.secret"
            );
            let verification_key =
                include_bytes!("../../../tests/assets/signing_keys/v6/rpm-testkey-v6-ed25519.asc");
            let verifier = Verifier::load_from_asc_bytes(verification_key.as_slice())
                .expect("PK parsing failed");
            let signer =
                Signer::load_from_asc_bytes(signing_key.as_slice()).expect("SK parsing failed");
            (signer, verifier)
        }

        #[test]
        fn sign_verify_roundtrip() {
            let (signer, verifier) = prep();
            super::sign_verify_roundtrip(&signer, &verifier);
        }

        #[test]
        fn sign_verify_roundtrip_with_subkey() {
            let (signer, verifier) = prep();

            // The v6 ed25519 test key has a signing subkey
            let signed_key = signer.signed_key.as_ref().unwrap();
            assert_eq!(signed_key.secret_subkeys.len(), 1, "expected one signing subkey");
            let subkey_fingerprint = signed_key.secret_subkeys[0].key.fingerprint();

            let signer = signer
                .with_signing_key(subkey_fingerprint.as_bytes())
                .expect("subkey selection should succeed");

            assert!(
                matches!(signer.signing_key, AnySigningKey::Sub(_)),
                "should be using a subkey"
            );

            super::sign_verify_roundtrip(&signer, &verifier);
        }

        #[test]
        fn with_signing_key_primary() {
            let (signer, verifier) = prep();

            let signed_key = signer.signed_key.as_ref().unwrap();
            let primary_fingerprint = signed_key.primary_key.fingerprint();

            let signer = signer
                .with_signing_key(primary_fingerprint.as_bytes())
                .expect("primary key selection should succeed");

            assert!(
                matches!(signer.signing_key, AnySigningKey::Primary(_)),
                "should be using the primary key"
            );

            super::sign_verify_roundtrip(&signer, &verifier);
        }

        #[test]
        fn with_signing_key_not_found() {
            let (signer, _verifier) = prep();
            let bogus_fingerprint = [0xDE, 0xAD, 0xBE, 0xEF];
            let result = signer.with_signing_key(&bogus_fingerprint);
            assert!(result.is_err(), "should fail with unknown fingerprint");
        }

        #[test]
        fn user_id_included_in_signature() {
            let (signer, _verifier) = prep();

            assert!(
                signer.user_id.is_some(),
                "user_id should be populated from the key"
            );

            let signature = signer
                .sign(Cursor::new(TEST_DATA), TEST_TIMESTAMP)
                .expect("signing should succeed");

            let parsed = Verifier::parse_signature(&signature).expect("should parse");
            let config = parsed.config().expect("should have config");
            let has_signer_uid = config
                .hashed_subpackets
                .iter()
                .any(|sp| matches!(sp.data, SubpacketData::SignersUserID(_)));
            assert!(has_signer_uid, "signature should contain SignersUserID subpacket");
        }
    }
}
