use std::collections::HashMap;
use std::path::Path;

use rpm::*;

mod common;

/// Tags that are expected to differ between built and fixture packages.
///
/// These include build-time metadata, build environment details, and signature
/// tags that vary with each build or build environment.
const EXPECTED_DIFFERENCES: &[u32] = &[
    // Build-time metadata
    IndexTag::RPMTAG_BUILDTIME as u32,
    IndexTag::RPMTAG_BUILDHOST as u32,
    IndexTag::RPMTAG_COOKIE as u32,
    IndexTag::RPMTAG_SOURCERPM as u32,
    // Build environment specifics
    IndexTag::RPMTAG_OPTFLAGS as u32, // Compiler flags from build env
    IndexTag::RPMTAG_PLATFORM as u32, // Platform string (e.g., x86_64-redhat-linux-gnu)
    IndexTag::RPMTAG_SOURCESIGMD5 as u32, // Source package signature
    IndexTag::RPMTAG_RPMVERSION as u32, // rpm-rs vs rpm version string
    IndexTag::RPMTAG_HEADERIMMUTABLE as u32, // Region tag computed from all other header tags
    IndexTag::RPMTAG_HEADERSIGNATURES as u32, // Region tag computed from all other signature tags
    // File classification tags - generated by rpm using libmagic; we don't replicate this
    // They are somewhat obscure and informational only - not worth a libmagic dependency.
    IndexTag::RPMTAG_FILECLASS as u32,
    IndexTag::RPMTAG_FILECOLORS as u32,
    IndexTag::RPMTAG_CLASSDICT as u32,
    IndexTag::RPMTAG_FILEMIMEINDEX as u32,
    IndexTag::RPMTAG_MIMEDICT as u32,
    // Signature tags (sign the entire package including buildtime/buildhost)
    IndexSignatureTag::RPMSIGTAG_SIZE as u32,
    IndexSignatureTag::RPMSIGTAG_SHA1 as u32,
    IndexSignatureTag::RPMSIGTAG_SHA256 as u32,
    IndexSignatureTag::RPMSIGTAG_SHA3_256 as u32,
    IndexSignatureTag::RPMSIGTAG_MD5 as u32,
];

#[derive(Debug)]
struct TagDifference {
    tag: u32,
    built_value: IndexData,
    fixture_value: IndexData,
}

#[derive(Debug)]
struct HeaderComparison {
    missing_in_built: Vec<(u32, IndexData)>,
    extra_in_built: Vec<(u32, IndexData)>,
    value_differences: Vec<TagDifference>,
    expected_differences: Vec<TagDifference>,
}

impl HeaderComparison {
    fn is_clean(&self) -> bool {
        self.missing_in_built.is_empty()
            && self.extra_in_built.is_empty()
            && self.value_differences.is_empty()
    }

    fn report(&self) -> String {
        fn item_count(data: &IndexData) -> usize {
            match data {
                IndexData::Null => 0,
                IndexData::Char(v) | IndexData::Int8(v) | IndexData::Bin(v) => v.len(),
                IndexData::Int16(v) => v.len(),
                IndexData::Int32(v) => v.len(),
                IndexData::Int64(v) => v.len(),
                IndexData::StringTag(_) => 1,
                IndexData::StringArray(v) | IndexData::I18NString(v) => v.len(),
            }
        }

        let mut output = String::new();

        if !self.missing_in_built.is_empty() {
            output.push_str("\nMissing tags in built package:\n");
            for (tag, data) in &self.missing_in_built {
                output.push_str(&format!("  {}: {:?}\n", format_tag_id(*tag), data));
            }
        }

        if !self.extra_in_built.is_empty() {
            output.push_str("\nExtra tags in built package:\n");
            for (tag, data) in &self.extra_in_built {
                output.push_str(&format!("  {}: {:?}\n", format_tag_id(*tag), data));
            }
        }

        if !self.value_differences.is_empty() {
            output.push_str("\nValue differences:\n");
            for diff in &self.value_differences {
                output.push_str(&format!("  {}:\n", format_tag_id(diff.tag)));
                output.push_str(&format!(
                    "    Built:   {:?} len: {}\n",
                    diff.built_value,
                    item_count(&diff.built_value),
                ));
                output.push_str(&format!(
                    "    Fixture: {:?} len: {}\n",
                    diff.fixture_value,
                    item_count(&diff.fixture_value),
                ));
            }
        }

        if !self.expected_differences.is_empty() {
            output.push_str(&format!(
                "\n{} expected differences (buildtime, signatures, etc.)\n",
                self.expected_differences.len()
            ));
        }

        output
    }
}

fn compare_headers<T: rpm::Tag>(
    built: &rpm::Header<T>,
    fixture: &rpm::Header<T>,
) -> Result<HeaderComparison, Box<dyn std::error::Error>> {
    let built_entries = built.get_all_entries()?;
    let fixture_entries = fixture.get_all_entries()?;

    let built_map: HashMap<u32, IndexData> = built_entries.into_iter().collect();
    let fixture_map: HashMap<u32, IndexData> = fixture_entries.into_iter().collect();

    let mut missing_in_built = Vec::new();
    let mut extra_in_built = Vec::new();
    let mut value_differences = Vec::new();
    let mut expected_differences = Vec::new();

    // Find tags in fixture but not in built
    for (tag, data) in &fixture_map {
        if !built_map.contains_key(tag) {
            if EXPECTED_DIFFERENCES.contains(tag) {
                // Expected to be missing
                continue;
            }
            missing_in_built.push((*tag, data.clone()));
        }
    }

    // Find tags in built but not in fixture, and compare values
    for (tag, built_data) in &built_map {
        match fixture_map.get(tag) {
            None => {
                if EXPECTED_DIFFERENCES.contains(tag) {
                    // Expected to be extra
                    continue;
                }
                extra_in_built.push((*tag, built_data.clone()));
            }
            Some(fixture_data) => {
                if built_data != fixture_data {
                    let diff = TagDifference {
                        tag: *tag,
                        built_value: built_data.clone(),
                        fixture_value: fixture_data.clone(),
                    };

                    if EXPECTED_DIFFERENCES.contains(tag) {
                        expected_differences.push(diff);
                    } else {
                        value_differences.push(diff);
                    }
                }
            }
        }
    }

    Ok(HeaderComparison {
        missing_in_built,
        extra_in_built,
        value_differences,
        expected_differences,
    })
}

/// Compare a built package against a fixture package and assert they match.
///
/// This compares both the header and signature sections, failing the test
/// with a detailed report if there are unexpected differences.
#[track_caller]
fn assert_packages_match(
    parsed: &Package,
    fixture: &Package,
    label: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let header_cmp = compare_headers(&parsed.metadata.header, &fixture.metadata.header)?;
    assert!(
        header_cmp.is_clean(),
        "===== Header comparison failed ({}) =====\n{}",
        label,
        header_cmp.report()
    );

    let sig_cmp = compare_headers(&parsed.metadata.signature, &fixture.metadata.signature)?;
    assert!(
        sig_cmp.is_clean(),
        "===== Signature comparison failed ({}) =====\n{}",
        label,
        sig_cmp.report()
    );

    assert_eq!(
        parsed.content,
        fixture.content,
        "===== Payload mismatch ({}) =====\nparsed {} bytes vs fixture {} bytes",
        label,
        parsed.content.len(),
        fixture.content.len(),
    );

    Ok(())
}

/// Build a package matching the rpm-empty.spec file.
///
/// This is the simplest possible RPM - no files, minimal metadata.
/// Tests both v4 and v6 package formats.
#[test]
fn test_build_rpm_empty() -> Result<(), Box<dyn std::error::Error>> {
    // Test v4
    let pkg_v4 = PackageBuilder::new("rpm-empty", "0", "LGPL", "x86_64", "")
        .using_config(
            BuildConfig::v4()
                .compression(CompressionType::None)
                .source_date(common::FIXTURE_SOURCE_DATE),
        )
        .release("0")
        .build()?;

    let mut buf = Vec::new();
    pkg_v4.write(&mut buf)?;
    let parsed_v4 = Package::parse(&mut buf.as_slice())?;
    assert_eq!(parsed_v4.metadata.get_file_entries()?.len(), 0);

    let fixture_v4 = Package::open(common::pkgs::v4::RPM_EMPTY)?;
    assert_packages_match(&parsed_v4, &fixture_v4, "v4")?;

    // Test v6
    let pkg_v6 = PackageBuilder::new("rpm-empty", "0", "LGPL", "x86_64", "")
        .using_config(
            BuildConfig::v6()
                .compression(CompressionType::None)
                .source_date(common::FIXTURE_SOURCE_DATE),
        )
        .release("0")
        .build()?;

    let mut buf = Vec::new();
    pkg_v6.write(&mut buf)?;
    let parsed_v6 = Package::parse(&mut buf.as_slice())?;
    assert_eq!(parsed_v6.metadata.get_file_entries()?.len(), 0);

    let fixture_v6 = Package::open(common::pkgs::v6::RPM_EMPTY)?;
    assert_packages_match(&parsed_v6, &fixture_v6, "v6")?;

    Ok(())
}

/// Build a package matching the rpm-basic.spec file.
///
/// This is a comprehensive test of many RPM features:
/// - Complex versioning (epoch, version, release)
/// - Multiple dependency types (requires, provides, obsoletes, conflicts, recommends, suggests, enhances, supplements)
/// - Rich dependencies
/// - Various file types and flags
/// - Multiple changelogs
/// - Extended metadata (vendor, packager, url, vcs, group)
/// Tests both v4 and v6 package formats.
#[test]
fn test_build_rpm_basic() -> Result<(), Box<dyn std::error::Error>> {
    use rpm::Dependency;

    let sources_dir = Path::new(common::CARGO_MANIFEST_DIR).join("tests/assets/SOURCES");
    let config_file = sources_dir.join("example_config.toml");
    let data_file = sources_dir.join("example_data.xml");
    let script_file = sources_dir.join("multiplication_tables.py");
    let module_dir = sources_dir.join("module");

    // Helper to build the package with a given config
    let build_pkg = |config: BuildConfig| -> Result<Package, Box<dyn std::error::Error>> {
        let pkg = PackageBuilder::new(
            "rpm-basic",
            "2.3.4",
            "MPL-2.0",
            "noarch",
            "A package for exercising basic features of RPM",
        )
        .using_config(config)
        .epoch(1)
        .release("5.el9")
        .description("This package attempts to exercise basic features of RPM packages.")
        .group("Development/Tools")
        .url("http://www.savewalterwhite.com/")
        .packager("Walter White")
        .vendor("Los Pollos Hermanos")
        .vcs("https://github.com/rpm-rs/rpm")
        // Requires dependencies
        .requires(Dependency::less_eq("morality", "2"))
        .requires(Dependency::greater_eq("methylamine", "1.0.0-1"))
        .requires(Dependency {
            name: "/usr/sbin/ego".to_string(),
            flags: DependencyFlags::SCRIPT_PRE,
            version: "".to_string(),
        })
        .requires(Dependency {
            name: "regret".to_string(),
            flags: DependencyFlags::SCRIPT_POST,
            version: "".to_string(),
        })
        // Provides dependencies
        .provides(Dependency::eq("shock", "33"))
        .provides(Dependency::any("aaronpaul"))
        .provides(Dependency::any("/usr/bin/ls"))
        .provides(Dependency::any("breaking(bad)"))
        // Obsoletes dependencies
        .obsoletes(Dependency::less("tucosalamanca", "444"))
        .obsoletes(Dependency::less("gusfring", "32.1-0"))
        // Conflicts
        .conflicts(Dependency::greater("hank", "35"))
        // Recommends (with rich dependency)
        .recommends(Dependency::greater("huel", "9:11.0-0"))
        .recommends(Dependency::any("SaulGoodman(CriminalLawyer)"))
        // Supplements
        .supplements(Dependency::eq("comedy", "0:11.1-4"))
        // Suggests
        .suggests(Dependency::any("chilipowder"))
        // Enhances
        .enhances(Dependency::greater("purity", "9000"))
        // OrderWithRequires
        .order_with_requires(Dependency::any("methylamine"))
        // Changelogs (in reverse chronological order)
        .add_changelog_entry(
            "Walter White <ww@savewalterwhite.com> - 3.3.3-3",
            "- I'm not in the meth business. I'm in the empire business.",
            1623672000, // Mon Jun 14 2021 12:00:00 UTC
        )
        .add_changelog_entry(
            "Gustavo Fring <gus@lospolloshermanos.com> - 2.2.2-2",
            "- Never Make The Same Mistake Twice.",
            1619352000, // Sun Apr 25 2021 12:00:00 UTC
        )
        .add_changelog_entry(
            "Mike Ehrmantraut <mike@lospolloshermanos.com> - 1.1.1-1",
            "- Just because you shot Jesse James, don't make you Jesse James.",
            1617192000, // Wed Mar 31 2021 12:00:00 UTC
        )
        // Files
        .with_file(
            &config_file,
            FileOptions::new("/etc/rpm-basic/example_config.toml").config(),
        )?
        .with_file(
            &data_file,
            FileOptions::new("/usr/share/rpm-basic/example_data.xml"),
        )?
        .with_file(&script_file, FileOptions::new("/usr/bin/rpm-basic"))?
        // Parent directory for module (matches spec: /usr/lib/%{name}/)
        .with_dir_entry(FileOptions::dir("/usr/lib/rpm-basic"))?
        .with_dir(&module_dir, "/usr/lib/rpm-basic/module", |o| o)?
        // Directories
        .with_dir_entry(FileOptions::dir("/var/tmp/rpm-basic"))?
        // Ghost file
        .with_ghost(FileOptions::ghost("/var/log/rpm-basic/basic.log"))?
        // Doc directory (created by %doc macro in spec file)
        .with_dir_entry(FileOptions::dir("/usr/share/doc/rpm-basic"))?
        // Doc file (README built during %build)
        .with_file_contents(
            "No more half measures, Walter.\n",
            FileOptions::new("/usr/share/doc/rpm-basic/README").doc(),
        )?
        .build()?;

        let mut buf = Vec::new();
        pkg.write(&mut buf)?;
        Ok(Package::parse(&mut buf.as_slice())?)
    };

    // Test v4
    let parsed_v4 = build_pkg(
        BuildConfig::v4()
            .compression(CompressionType::None)
            .source_date(common::FIXTURE_SOURCE_DATE),
    )?;
    let fixture_v4 = Package::open(common::pkgs::v4::RPM_BASIC)?;
    assert_packages_match(&parsed_v4, &fixture_v4, "v4")?;

    // Test v6
    let parsed_v6 = build_pkg(
        BuildConfig::v6()
            .compression(CompressionType::None)
            .source_date(common::FIXTURE_SOURCE_DATE),
    )?;
    let fixture_v6 = Package::open(common::pkgs::v6::RPM_BASIC)?;
    assert_packages_match(&parsed_v6, &fixture_v6, "v6")?;

    Ok(())
}

/// Build a package matching the rpm-file-attrs.spec file.
///
/// Tests various file attributes:
/// - normal files and directories
/// - symlinks
/// - virtual attributes (%dir, %artifact, %config, %doc, %ghost, %license, etc.)
/// - ownership and permissions (%attr)
/// - file capabilities (%caps)
/// - verify flags (%verify)
#[test]
fn test_build_rpm_file_attrs() -> Result<(), Box<dyn std::error::Error>> {
    let pkg = PackageBuilder::new(
        "rpm-file-attrs",
        "1.0",
        "MIT",
        "noarch",
        "Test RPM file attributes",
    )
    .using_config(
        BuildConfig::v6()
            .compression(CompressionType::None)
            .source_date(common::FIXTURE_SOURCE_DATE),
    )
    .release("1")
    // Parent directory marked with %dir
    .with_dir_entry(FileOptions::dir("/opt/rpm-file-attrs"))?
    // Normal files
    .with_file_contents("normal\n", FileOptions::new("/opt/rpm-file-attrs/normal"))?
    .with_dir_entry(FileOptions::dir("/opt/rpm-file-attrs/dir"))?
    .with_file_contents(
        "file-in-a-dir\n",
        FileOptions::new("/opt/rpm-file-attrs/dir/normal"),
    )?
    // Symlinks
    .with_symlink(FileOptions::symlink(
        "/opt/rpm-file-attrs/symlink",
        "normal",
    ))?
    .with_dir_entry(FileOptions::dir("/opt/rpm-file-attrs/symlink_dir"))?
    .with_symlink(FileOptions::symlink(
        "/opt/rpm-file-attrs/symlink_dir/dir",
        "../dir",
    ))?
    // Virtual attributes
    .with_file_contents(
        "artifact\n",
        FileOptions::new("/opt/rpm-file-attrs/artifact").artifact(),
    )?
    .with_file_contents(
        "config\n",
        FileOptions::new("/opt/rpm-file-attrs/config").config(),
    )?
    .with_file_contents(
        "config_noreplace\n",
        FileOptions::new("/opt/rpm-file-attrs/config_noreplace")
            .config()
            .noreplace(),
    )?
    .with_file_contents("doc\n", FileOptions::new("/opt/rpm-file-attrs/doc").doc())?
    .with_ghost(FileOptions::ghost("/opt/rpm-file-attrs/ghost"))?
    .with_file_contents(
        "license\n",
        FileOptions::new("/opt/rpm-file-attrs/license").license(),
    )?
    .with_file_contents(
        "missingok\n",
        FileOptions::new("/opt/rpm-file-attrs/missingok").missingok(),
    )?
    .with_file_contents(
        "readme\n",
        #[allow(deprecated)]
        FileOptions::new("/opt/rpm-file-attrs/readme").readme(),
    )?
    // Owner, group and permissions
    .with_file_contents(
        "example-binary\n",
        FileOptions::new("/opt/rpm-file-attrs/example-binary")
            .permissions(0o644)
            .user("root")
            .group("root"),
    )?
    .with_file_contents(
        "example-confidential-file\n",
        FileOptions::new("/opt/rpm-file-attrs/example-confidential-file")
            .permissions(0o600)
            .user("jane")
            .group("jane"),
    )?
    .with_file_contents(
        "different-owner-and-group\n",
        FileOptions::new("/opt/rpm-file-attrs/different-owner-and-group")
            .permissions(0o655)
            .user("jane")
            .group("bob"),
    )?
    // Capabilities
    .with_file_contents(
        "empty_caps\n",
        FileOptions::new("/opt/rpm-file-attrs/empty_caps")
            .permissions(0o655)
            .user("root")
            .group("root")
            .caps("=")?,
    )?
    .with_file_contents(
        "empty_caps2\n",
        FileOptions::new("/opt/rpm-file-attrs/empty_caps2")
            .permissions(0o655)
            .user("root")
            .group("root")
            .caps("")?,
    )?
    .with_file_contents(
        "with_caps\n",
        FileOptions::new("/opt/rpm-file-attrs/with_caps")
            .permissions(0o655)
            .user("root")
            .group("root")
            .caps("cap_sys_admin,cap_sys_ptrace=pe")?,
    )?
    // sysusers.d config for non-root owners
    .with_file_contents(
        "u jane - \"Jane user\"\ng bob - \"Bob group\"\nu bob - \"Bob user\"\n",
        FileOptions::new("/usr/lib/sysusers.d/rpm-file-attrs.conf"),
    )?
    // Verify flags
    .with_file_contents(
        "verify_some\n",
        FileOptions::new("/opt/rpm-file-attrs/verify_some").verify(
            FileVerifyFlags::FILEDIGEST | FileVerifyFlags::FILESIZE | FileVerifyFlags::MTIME,
        ),
    )?
    .with_file_contents(
        "verify_not\n",
        // %verify(not md5 size) — all bits set except md5 and size
        FileOptions::new("/opt/rpm-file-attrs/verify_not").verify(
            FileVerifyFlags::from_bits_retain(
                !(FileVerifyFlags::FILEDIGEST | FileVerifyFlags::FILESIZE).bits(),
            ),
        ),
    )?
    .with_file_contents(
        "verify_all\n",
        FileOptions::new("/opt/rpm-file-attrs/verify_all").verify(
            FileVerifyFlags::FILEDIGEST
                | FileVerifyFlags::FILESIZE
                | FileVerifyFlags::MODE
                | FileVerifyFlags::MTIME
                | FileVerifyFlags::RDEV
                | FileVerifyFlags::USER
                | FileVerifyFlags::GROUP
                | FileVerifyFlags::LINKTO,
        ),
    )?
    .with_file_contents(
        "verify_none\n",
        // %verify(not md5 size mode mtime rdev user group link) — all bits set except these 8
        FileOptions::new("/opt/rpm-file-attrs/verify_none").verify(
            FileVerifyFlags::from_bits_retain(
                !(FileVerifyFlags::FILEDIGEST
                    | FileVerifyFlags::FILESIZE
                    | FileVerifyFlags::MODE
                    | FileVerifyFlags::MTIME
                    | FileVerifyFlags::RDEV
                    | FileVerifyFlags::USER
                    | FileVerifyFlags::GROUP
                    | FileVerifyFlags::LINKTO)
                    .bits(),
            ),
        ),
    )?
    .build()?;

    // Write and re-read the package
    let mut buf = Vec::new();
    pkg.write(&mut buf)?;
    let parsed = Package::parse(&mut buf.as_slice())?;

    // Compare with fixture package
    let fixture = Package::open(common::pkgs::v6::RPM_FILE_ATTRS)?;
    assert_packages_match(&parsed, &fixture, "v6")?;

    Ok(())
}

/// Build a package matching the rpm-file-types.spec file.
///
/// Tests handling of different file content types:
/// - empty file
/// - binary file (PNG image)
/// - file with special characters in name
#[test]
fn test_build_rpm_file_types() -> Result<(), Box<dyn std::error::Error>> {
    let sources_dir = Path::new(common::CARGO_MANIFEST_DIR).join("tests/assets/SOURCES");
    let empty_file = sources_dir.join("empty_file");
    let image_file = sources_dir.join("rpm-rs-logo.png");
    let special_file = sources_dir.join("file with spaces & special (chars).txt");

    let pkg = PackageBuilder::new(
        "rpm-file-types",
        "1.0",
        "MIT",
        "noarch",
        "Test RPM handling of various file content types and paths",
    )
    .using_config(BuildConfig::v6().compression(CompressionType::None).source_date(common::FIXTURE_SOURCE_DATE))
    .epoch(0)
    .release("1")
    .description("A package for exercising RPM handling of different file content types\nand unusual file paths.")
    .with_file(
        &empty_file,
        FileOptions::new("/opt/rpm-file-types/empty_file"),
    )?
    .with_file(
        &image_file,
        FileOptions::new("/opt/rpm-file-types/rpm-rs-logo.png"),
    )?
    .with_file(
        &special_file,
        FileOptions::new("/opt/rpm-file-types/file with spaces & special (chars).txt"),
    )?
    .build()?;

    // Write and re-read the package
    let mut buf = Vec::new();
    pkg.write(&mut buf)?;
    let parsed = Package::parse(&mut buf.as_slice())?;

    // Compare with fixture package
    let fixture = Package::open(common::pkgs::v6::RPM_FILE_TYPES)?;
    assert_packages_match(&parsed, &fixture, "v6")?;

    Ok(())
}

/// Build a package matching the rpm-scriptlets.spec file.
///
/// Tests scriptlets, triggers, file triggers, and transaction file triggers.
#[test]
fn test_build_rpm_scriptlets() -> Result<(), Box<dyn std::error::Error>> {
    use rpm::Dependency;

    // Create a temp file with the content RPM would generate
    let temp_dir = std::env::temp_dir().join("rpm-rs-scriptlets-test");
    std::fs::create_dir_all(&temp_dir)?;
    let data_path = temp_dir.join("data");
    std::fs::write(&data_path, "scriptlet-test\n")?;

    let pkg = PackageBuilder::new(
        "rpm-scriptlets",
        "1.0",
        "MIT",
        "noarch",
        "Test RPM scriptlets and triggers",
    )
    .using_config(
        BuildConfig::v6()
            .compression(CompressionType::None)
            .source_date(common::FIXTURE_SOURCE_DATE),
    )
    .release("1")
    .description("A package for exercising RPM scriptlets, triggers, and file triggers.")
    // Interpreter requires are auto-generated by the builder for each scriptlet.
    // The bare INTERP require is for the explicit -p /bin/sh on %post.
    .requires(Dependency::interp("/bin/sh"))
    // Scriptlets — bodies include trailing comments as RPM includes them
    .pre_install_script(
        Scriptlet::new("echo \"pre-install\"\n\n# Explicit interpreter").prog(vec!["/bin/sh"]),
    )
    .post_install_script(Scriptlet::new("echo \"post-install\"").prog(vec!["/bin/sh"]))
    .pre_uninstall_script(Scriptlet::new("echo \"pre-uninstall\"").prog(vec!["/bin/sh"]))
    .post_uninstall_script(
        Scriptlet::new("echo \"post-uninstall\"\n\n# Transaction-level scriptlets")
            .prog(vec!["/bin/sh"]),
    )
    .pre_trans_script(Scriptlet::new("echo \"pre-transaction\"").prog(vec!["/bin/sh"]))
    .post_trans_script(
        Scriptlet::new("echo \"post-transaction\"\n\n# Verify scriptlet").prog(vec!["/bin/sh"]),
    )
    .verify_script(
        Scriptlet::new("echo \"verify\"\n\n# Triggers (against a hypothetical target package)")
            .prog(vec!["/bin/sh"]),
    )
    // Package triggers
    .trigger_prein(
        "bash",
        None,
        Scriptlet::new("echo \"trigger-pre-install on bash\""),
    )
    .trigger_in(
        "bash",
        Some((DependencyFlags::GREATER, "5.0")),
        Scriptlet::new("echo \"trigger-install on bash > 5.0\""),
    )
    .trigger_un(
        "bash",
        Some((DependencyFlags::LE, "6.0")),
        Scriptlet::new("echo \"trigger-uninstall on bash <= 6.0\""),
    )
    .trigger_postun(
        "bash",
        None,
        Scriptlet::new("echo \"trigger-post-uninstall on bash\"\n\n# File triggers"),
    )
    // File triggers
    .file_trigger_in(
        "/usr/lib",
        None,
        Scriptlet::new("echo \"file-trigger-install in /usr/lib\""),
    )
    .file_trigger_un(
        "/usr/lib",
        None,
        Scriptlet::new("echo \"file-trigger-uninstall in /usr/lib\""),
    )
    .file_trigger_postun(
        "/usr/lib",
        None,
        Scriptlet::new(
            "echo \"file-trigger-post-uninstall in /usr/lib\"\n\n# Transaction-level file triggers",
        ),
    )
    // Transaction file triggers
    .trans_file_trigger_in(
        "/usr/bin",
        None,
        Scriptlet::new("echo \"trans-file-trigger-install in /usr/bin\""),
    )
    .trans_file_trigger_un(
        "/usr/bin",
        None,
        Scriptlet::new("echo \"trans-file-trigger-uninstall in /usr/bin\""),
    )
    .trans_file_trigger_postun(
        "/usr/bin",
        None,
        Scriptlet::new("echo \"trans-file-trigger-post-uninstall in /usr/bin\""),
    )
    // File
    .with_file(&data_path, FileOptions::new("/opt/rpm-scriptlets/data"))?
    .build()?;

    // Clean up temp file
    std::fs::remove_dir_all(&temp_dir)?;

    // Write and re-read the package
    let mut buf = Vec::new();
    pkg.write(&mut buf)?;
    let parsed = Package::parse(&mut buf.as_slice())?;

    // Compare with fixture package
    let fixture = Package::open(common::pkgs::v6::RPM_SCRIPTLETS)?;
    assert_packages_match(&parsed, &fixture, "v6")?;

    Ok(())
}

/// Build a package matching the rpm-rich-deps.spec file.
///
/// Tests rich (boolean) dependencies across all dependency types.
#[test]
fn test_build_rpm_rich_deps() -> Result<(), Box<dyn std::error::Error>> {
    use rpm::Dependency;

    let temp_dir = std::env::temp_dir().join("rpm-rs-rich-deps-test");
    std::fs::create_dir_all(&temp_dir)?;
    let data_path = temp_dir.join("data");
    std::fs::write(&data_path, "rich-deps-test\n")?;

    let pkg = PackageBuilder::new(
        "rpm-rich-deps",
        "1.0",
        "MIT",
        "noarch",
        "Test RPM rich (boolean) dependencies",
    )
    .using_config(
        BuildConfig::v6()
            .compression(CompressionType::None)
            .source_date(common::FIXTURE_SOURCE_DATE),
    )
    .release("1")
    .description(
        "A package for exercising RPM rich (boolean) dependency syntax,\n\
         including all boolean operators and nesting.",
    )
    // Boolean operators
    .requires(Dependency::any("(pkgA or pkgB)"))
    .requires(Dependency::any("(pkgC and pkgD)"))
    .requires(Dependency::any("(pkgE if pkgF)"))
    .requires(Dependency::any("(pkgG if pkgH else pkgI)"))
    .supplements(Dependency::any("(pkgJ unless pkgK)"))
    .conflicts(Dependency::any("(pkgL unless pkgM else pkgN)"))
    .requires(Dependency::any("(pkgO with pkgP)"))
    .requires(Dependency::any("(pkgQ without pkgR)"))
    // Nested boolean expressions
    .requires(Dependency::any("((pkgS or pkgT) and pkgU)"))
    .requires(Dependency::any("(pkgV or (pkgW and pkgX))"))
    .recommends(Dependency::any("((pkgY and pkgZ) or pkgAA)"))
    // Boolean deps with version constraints
    .requires(Dependency::any("(pkgBB >= 2.0 or pkgCC >= 3.0)"))
    .requires(Dependency::any("(pkgDD >= 1.0 and pkgEE < 5.0)"))
    .requires(Dependency::any("(pkgFF >= 2.0 if pkgGG >= 1.0)"))
    // Rich deps in other dependency types
    .recommends(Dependency::any("(pkgHH or pkgII)"))
    .suggests(Dependency::any("(pkgJJ if pkgKK)"))
    .supplements(Dependency::any("(pkgLL and pkgMM)"))
    .enhances(Dependency::any("(pkgNN or pkgOO)"))
    .conflicts(Dependency::any("(pkgPP and pkgQQ)"))
    // File
    .with_file(&data_path, FileOptions::new("/opt/rpm-rich-deps/data"))?
    .build()?;

    // Clean up temp files
    std::fs::remove_dir_all(&temp_dir)?;

    // Write and re-read the package
    let mut buf = Vec::new();
    pkg.write(&mut buf)?;
    let parsed = Package::parse(&mut buf.as_slice())?;

    // Compare with fixture package
    let fixture = Package::open(common::pkgs::v6::RPM_RICH_DEPS)?;
    assert_packages_match(&parsed, &fixture, "v6")?;

    Ok(())
}

/// Test that reading and writing RPM files is lossless.
///
/// Parse all test fixture RPM files, write them out, and verify the checksum
/// of the written file matches the original.
#[test]
fn test_roundtrip_all_fixtures() -> Result<(), Box<dyn std::error::Error>> {
    use sha2::{Digest, Sha256};
    use std::fs;
    use std::io::Write;

    let fixtures = vec![
        // V4 binary packages
        common::pkgs::v4::RPM_EMPTY,
        common::pkgs::v4::RPM_BASIC,
        common::pkgs::v4::RPM_BASIC_RSA_SIGNED,
        common::pkgs::v4::RPM_BASIC_ECDSA_SIGNED,
        common::pkgs::v4::RPM_BASIC_EDDSA_SIGNED,
        common::pkgs::v4::RPM_BASIC_IMA_SIGNED,
        // V4 source packages
        common::pkgs::v4::src::RPM_EMPTY_SRC,
        common::pkgs::v4::src::RPM_BASIC_SRC,
        // V6 binary packages
        common::pkgs::v6::RPM_EMPTY,
        common::pkgs::v6::RPM_BASIC,
        common::pkgs::v6::RPM_FILE_ATTRS,
        common::pkgs::v6::RPM_FILE_TYPES,
        common::pkgs::v6::RPM_HARDLINKS,
        common::pkgs::v6::RPM_I18N,
        common::pkgs::v6::RPM_RICH_DEPS,
        common::pkgs::v6::RPM_SCRIPTLETS,
        common::pkgs::v6::RPM_WITH_PATCH,
        common::pkgs::v6::RPM_BASIC_RSA_SIGNED,
        common::pkgs::v6::RPM_BASIC_EDDSA_SIGNED,
        common::pkgs::v6::RPM_BASIC_MLDSA_SIGNED,
        common::pkgs::v6::RPM_BASIC_MULTI_SIGNED,
        // V6 compressed packages
        common::pkgs::v6::compressed::RPM_BASIC_GZIP,
        common::pkgs::v6::compressed::RPM_BASIC_ZSTD,
        common::pkgs::v6::compressed::RPM_BASIC_XZ,
        // V6 source packages
        common::pkgs::v6::src::RPM_EMPTY_SRC,
        common::pkgs::v6::src::RPM_BASIC_SRC,
        common::pkgs::v6::src::RPM_FILE_ATTRS_SRC,
        common::pkgs::v6::src::RPM_FILE_TYPES_SRC,
        common::pkgs::v6::src::RPM_HARDLINKS_SRC,
    ];

    let temp_dir = std::env::temp_dir().join("rpm-rs-roundtrip-test");
    fs::create_dir_all(&temp_dir)?;

    // TODO: what we really need this test to do, is rebuild the headers from the original headers, that way we can
    // check that the padding calculation and such is actually identical between rpm-rs and rpm
    for fixture_path in fixtures {
        // Compute original checksum
        let original_bytes = fs::read(fixture_path)?;
        let original_hash = Sha256::digest(&original_bytes);

        // Parse the package
        let pkg = Package::open(fixture_path)?;

        // Write to temp file
        let file_name = Path::new(fixture_path)
            .file_name()
            .unwrap()
            .to_string_lossy();
        let temp_path = temp_dir.join(file_name.as_ref());
        let mut temp_file = fs::File::create(&temp_path)?;
        pkg.write(&mut temp_file)?;
        temp_file.flush()?;
        drop(temp_file);

        // Compute written checksum
        let written_bytes = fs::read(&temp_path)?;
        let written_hash = Sha256::digest(&written_bytes);

        // Compare
        assert_eq!(
            original_hash, written_hash,
            "Roundtrip checksum mismatch for {}",
            fixture_path
        );

        // Clean up
        fs::remove_file(&temp_path)?;
    }

    fs::remove_dir(&temp_dir)?;
    Ok(())
}
